version: "3.6"
services:
  prod:
    image: tons/git-release
    build: .

  test:
    build:
      context: .
      target: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'go test -v ./...'
